SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) * PRICE  AS SALES
FROM PRODUCT LEFT JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
HAVING ISNULL(SALES) = FALSE
ORDER BY SALES DESC, PRODUCT_CODE