SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, IFNULL(USER_ID, NULL) AS USER_ID, SALES_AMOUNT
FROM
(SELECT PRODUCT_ID, SALES_AMOUNT, SALES_DATE, USER_ID
FROM ONLINE_SALE 
UNION
SELECT PRODUCT_ID, SALES_AMOUNT, SALES_DATE, NULL
FROM OFFLINE_SALE) A
WHERE MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID