SELECT CAR_ID, CAR_TYPE, ROUND(FEE) AS FEE
FROM(
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * ((100-CP.DISCOUNT_RATE) * 0.01) * 30 AS FEE
FROM (
SELECT CC.CAR_ID, MAX(CR.END_DATE) AS MAX_DATE, CC.CAR_TYPE, CC.DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR AS CC LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CR ON CC.CAR_ID = CR.CAR_ID
WHERE CC.CAR_TYPE IN ("세단", "SUV")
GROUP BY CC.CAR_ID
)AS A INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  AS CP ON A.CAR_TYPE = CP.CAR_TYPE
WHERE CP.DURATION_TYPE LIKE "%30%" AND MAX_DATE < "2022-11-01"
) RES
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

