SELECT A.FOOD_TYPE, B.REST_ID, B.REST_NAME, A.FAVORITES
FROM 
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
) AS A INNER JOIN REST_INFO AS B ON A.FAVORITES = B.FAVORITES
GROUP BY A.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC
