SELECT DISTINCT DEVELOPERS.ID, DEVELOPERS.EMAIL, DEVELOPERS.FIRST_NAME, DEVELOPERS.LAST_NAME
FROM DEVELOPERS JOIN SKILLCODES ON SKILLCODES.CODE <= DEVELOPERS.SKILL_CODE
WHERE SKILLCODES.CODE & DEVELOPERS.SKILL_CODE  > 0 AND CATEGORY = "Front End"
ORDER BY ID