SELECT RES.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, DATE_FORMAT(REST_REVIEW.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM (
SELECT MP.MEMBER_ID, MP.MEMBER_NAME, COUNT(*) AS CNT
FROM MEMBER_PROFILE AS MP LEFT JOIN REST_REVIEW AS RR ON MP.MEMBER_ID = RR.MEMBER_ID
GROUP BY MP.MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1
) AS RES INNER JOIN REST_REVIEW  ON RES.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT