SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO AS A LEFT JOIN ITEM_TREE AS B ON A.ITEM_ID = B.PARENT_ITEM_ID LEFT JOIN ITEM_INFO AS C ON B.ITEM_ID = C.ITEM_ID
WHERE A.RARITY = "RARE" AND ISNULL(C.ITEM_ID) = FALSE
ORDER BY C.ITEM_ID DESC