SELECT DISTINCT  A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM (
SELECT *
FROM DEVELOPERS JOIN SKILLCODES ON  SKILLCODES.CODE <= DEVELOPERS.SKILL_CODE ) AS A
WHERE A.SKILL_CODE & A.CODE > 0 AND (A.NAME = 'Python' OR A.NAME = 'C#')
ORDER BY A.ID