SELECT EXTRACT(YEAR FROM ECOLI_DATA.DIFFERENTIATION_DATE) AS YEAR, MD.M - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA JOIN (
SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS Y , MAX(SIZE_OF_COLONY) AS M
FROM ECOLI_DATA
GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE) ) AS MD
ON EXTRACT(YEAR FROM ECOLI_DATA.DIFFERENTIATION_DATE) = MD.Y
ORDER BY YEAR, YEAR_DEV
