SELECT DISTINCT CH.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH LEFT OUTER JOIN  CAR_RENTAL_COMPANY_CAR AS CC ON CH.CAR_ID = CC.CAR_ID
WHERE DATE_FORMAT(CH.START_DATE, "%Y-%m-%d") >= "2022-10-01" AND CC.CAR_TYPE = "세단"
ORDER BY CH.CAR_ID DESC