SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(FOOD_PRODUCT.PRICE * A.AMOUNT) AS TOTAL_SALES
FROM (SELECT * FROM FOOD_ORDER WHERE PRODUCE_DATE LIKE '2022-05-%' ) AS A
INNER JOIN FOOD_PRODUCT
    ON A.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID 
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID